version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: flagsdb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    build: .
    volumes:
      - .:/app
    command: ["/migrate", "-path", "migrations", "-database", "mysql://root:password@tcp(db:3306)/flagchain_db?multiStatements=true", "up"]
    depends_on:
      - db
    ports:
      - "8080:8080"
volumes:
  db_data: